Repository andela/taps-client, pull requests merged in 2018-10, with the labels that each got.

#23 #161072467 Provide visual feedback when creating team
  client/public/resources/images/failed.png
  client/public/resources/images/github.png
  client/public/resources/images/passed.png
  client/public/resources/images/team.png
  client/src/modules/CreateTeam/components/Form.jsx
  client/src/modules/CreateTeam/container/index.jsx
  client/src/redux/actions/index.js
  client/src/redux/actions/teams/index.js
  client/src/redux/actions/types.js
  client/src/redux/reducers/teamsReducer.js
  client/src/setupEnzyme.js
  client/src/tests/__mocks__/__mockData__/createTeamMock.js
  client/src/tests/__mocks__/assetsTransformer.js
  client/src/tests/__mocks__/mockLocalStorage.js
  client/src/tests/modules/createTeams/component/form.test.js
  client/src/tests/modules/createTeams/container/index.test.js
  client/src/tests/redux/reducers/teamReducer.test.js
  client/src/toasts/VisualFeedback.js
  client/styles/components/_create_team.scss
  jest.config.js
  package-lock.json
  package.json
Labels: Ready for merge

#22 #161059614 Member should be able to create permission request
  client/src/modules/common/Navbar/index.jsx
  client/src/redux/actions/requests/index.js
  client/src/redux/actions/types.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/requestsReducer.js
  client/src/tests/__mockData__/requestsMock.js
  client/src/tests/redux/actions/requests/index.test.js
  client/src/tests/redux/reducers/requestsReducer.test.js
  client/src/utils/errorFormatter.json
  client/styles/components/_navbar.scss
  package-lock.json
  package.json
Labels: Ready for merge

#19 #161115790 Add test for Auth module
  client/src/modules/Auth/container/index.jsx
  client/src/tests/modules/auth/authMockData.js
  client/src/tests/modules/auth/components/Extraform.test.jsx
  client/src/tests/modules/auth/components/GoogleButton.test.jsx
  client/src/tests/modules/auth/container/index.test.jsx
  package-lock.json
Labels: Ready for merge

#16 #160928262 Test files in Home module
  client/src/modules/Home/components/CardItem.jsx
  client/src/modules/Home/components/Cards.jsx
  client/src/modules/Home/container/index.jsx
  client/src/tests/modules/Home/components/Card.test.jsx
  client/src/tests/modules/Home/components/CardItem.test.jsx
  client/src/tests/modules/Home/container/index.test.jsx
  package-lock.json
Labels: Ready for merge

#29 #161117046 Common Module Tests
  client/src/modules/common/Modals/AddIntegration.jsx
  client/src/modules/common/Navbar/index.jsx
  client/src/modules/common/Preloader/index.jsx
  client/src/tests/modules/common/Footer/index.test.jsx
  client/src/tests/modules/common/Modals/AddIntegration.test.jsx
  client/src/tests/modules/common/Modals/AddMember.test.jsx
  client/src/tests/modules/common/Navbar/index.test.jsx
  client/src/tests/modules/common/Preloader/index.test.jsx
  client/src/tests/modules/common/Spinner/Spinner.test.jsx
Labels: Ready for code review

#18 #161116965 Create tests for create team module
  client/src/modules/CreateTeam/container/index.jsx
  client/src/tests/mock.js
  client/src/tests/modules/CreateTeam/components/Form.test.jsx
  client/src/tests/modules/CreateTeam/container/index.test.jsx
  client/src/tests/modules/CreateTeam/mock/containerMock.js
  client/src/tests/modules/createTeams/component/form.test.js
  client/src/tests/modules/createTeams/container/index.test.js
  jest.config.js
  package-lock.json
Labels: Ready for merge

#28 #161173843 Remove toast notification
  client/src/modules/common/Navbar/index.jsx
  client/src/redux/actions/index.js
  client/src/redux/actions/types.js
  client/src/redux/reducers/requestsReducer.js
Labels: Ready for merge

#35 #161157079 Create pivotal tracker project from create team form
  client/src/modules/CreateTeam/components/Form.jsx
  client/src/modules/CreateTeam/container/index.jsx
  client/src/redux/actions/teams/index.js
  client/src/tests/__mocks__/__mockData__/createTeamMock.js
  client/src/tests/modules/createTeams/component/form.test.js
  client/src/tests/redux/actions/teams/index.test.js
  client/src/tests/toasts.js/VisualFeedback.test.js
  client/src/toasts/VisualFeedback.js
  client/src/toasts/VisualFeedback.jsx
  client/src/utils/api.js
Labels: Ready for merge

#20 #161121591 Add tests for modules/Hoc folder
  client/src/modules/HOC/index.jsx
  client/src/tests/modules/hoc/hocMockData.js
  client/src/tests/modules/hoc/index.test.jsx
  package-lock.json
Labels: Ready for merge

#33 #161204910 Change tooltip list-style-type
  client/src/modules/Auth/components/ExtraForm.jsx
  client/styles/components/_form.scss
Labels: Ready for code review

#30 #161178600 Fix admin request success message and move requestMock file
  client/src/modules/common/Navbar/index.jsx
  client/src/tests/__mocks__/__mockData__/requestsMock.js
  client/src/tests/redux/actions/requests/index.test.js
  client/src/tests/redux/reducers/requestsReducer.test.js
Labels: Ready for merge

#37 #161199259 Create slack channel from create team form
  client/src/modules/CreateTeam/components/Form.jsx
  client/src/modules/CreateTeam/container/index.jsx
  client/src/redux/actions/teams/index.js
  client/src/tests/__mocks__/__mockData__/createTeamMock.js
  client/src/tests/redux/actions/teams/index.test.js
Labels: Ready for merge

#34 #161163483 Test redux actions and reducers for auth
  client/src/tests/redux/actions/auth/authAction.test.jsx
  client/src/tests/redux/actions/auth/authActionMockData.js
  client/src/tests/redux/reducers/authReducer.test.jsx
Labels: Ready for merge

#38 #161216329: Fix correct route bug
  client/src/routes/AuthRoute.jsx
  client/src/routes/index.jsx
  client/src/tests/__mocks__/mockLocalStorage.js
  client/src/tests/routes/AuthRoute.test.jsx
  jest.config.js
Labels: Ready for code review

#44 #161236513 Add project-name input field to create-team form
  client/src/modules/CreateTeam/components/Form.jsx
  client/src/modules/CreateTeam/container/index.jsx
  client/src/tests/modules/CreateTeam/components/Form.test.jsx
  client/src/tests/modules/createTeams/component/form.test.js
  client/src/utils/conventions.js
  client/src/utils/format.js
  client/styles/components/_create_team.scss
Labels: Ready for merge

#52 #161318186: corrects route bug
  client/src/routes/AuthRoute.jsx
  client/src/routes/index.jsx
  client/src/tests/__mocks__/mockLocalStorage.js
  client/src/tests/routes/AuthRoute.test.jsx
Labels: Ready for code review

#41 #161217628 User can search instantly on the homepage
  client/src/modules/Home/container/index.jsx
  client/src/modules/common/Navbar/index.jsx
  package.json
Labels: Ready for code review

#40 #161237365 Fix the favorite icon tooltip messages
  client/src/modules/HOC/index.jsx
  client/src/modules/Home/components/CardItem.jsx
  client/src/modules/Teams/components/FavoriteTeams.jsx
Labels: Ready for merge

#50 #161286798 Disable Request admin privilege button
  client/src/modules/common/Navbar/index.jsx
  client/src/redux/actions/requests/index.js
  client/src/redux/actions/types.js
  client/src/redux/reducers/requestsReducer.js
  client/src/tests/__mocks__/__mockData__/requestsMock.js
  client/src/tests/redux/actions/requests/index.test.js
  client/src/tests/redux/reducers/requestsReducer.test.js
  client/styles/components/_navbar.scss
Labels: Ready for merge

#45 #161257375 Implement redesign of add integration popup
  client/src/modules/Teams/components/Account.jsx
  client/src/modules/common/Modals/AddIntegration.jsx
  client/src/tests/modules/common/modals/addIntegration.test.js
  client/styles/components/_teams.scss
Labels: Ready for merge

#47 #161285197 Add a 404 page for invalid routes
  client/public/resources/images/404-Logo.png
  client/src/modules/common/404/index.jsx
  client/src/routes/index.jsx
  client/src/tests/modules/common/404/index.test.jsx
  client/styles/base/_util.scss
Labels: Ready for merge

#54 #161319351: update request reducer and action
  client/src/modules/common/Navbar/index.jsx
  client/src/redux/actions/requests/index.js
  client/src/redux/actions/types.js
  client/src/redux/reducers/requestsReducer.js
  client/src/tests/redux/actions/requests/index.test.js
  client/src/tests/redux/reducers/requestsReducer.test.js
  jest.config.js
  package-lock.json
Labels: Ready for code review

#36 #161178877: test user reducer and action
  client/src/tests/redux/actions/users/index.test.js
  client/src/tests/redux/reducers/userReducer.test.js
Labels: Ready for merge

#57 #161342131 Fix the 404 error page write-up
  client/src/modules/common/404/index.jsx
Labels: Ready for merge

#55 #161223150 Create admin request page
  client/src/modules/Admin/components/AdminRequest.jsx
  client/src/modules/Admin/components/RequestCheckbox.jsx
  client/src/modules/Admin/components/RequestHolder.jsx
  client/src/modules/HOC/withRequests.jsx
  client/src/modules/common/Navbar/index.jsx
  client/src/modules/common/Pagination/index.jsx
  client/src/routes/index.jsx
  client/src/tests/modules/Admin/components/AdminRequests.test.jsx
  client/src/tests/modules/Admin/components/RequestCheckbox.test.jsx
  client/src/tests/modules/Admin/components/RequestHolder.test.jsx
  client/src/tests/modules/Admin/mock/mockData.js
  client/src/tests/modules/HOC/withRequests.test.jsx
  client/src/tests/modules/common/Pagination/index.test.jsx
  client/styles/base/_settings.scss
  client/styles/base/_util.scss
  client/styles/components/_admin_request.scss
  client/styles/components/_navbar.scss
  client/styles/styles.scss
Labels: Ready for merge

#32 #161161961 Teams Module Tests
  client/src/modules/Teams/components/FavoriteTeams.jsx
  client/src/modules/common/Modals/AddIntegration.jsx
  client/src/tests/modules/teams/components/Account.test.jsx
  client/src/tests/modules/teams/components/FavoriteTeams.test.jsx
  client/src/tests/modules/teams/components/Form.test.jsx
  client/src/tests/modules/teams/components/Gallery.test.jsx
  client/src/tests/modules/teams/components/Member.test.jsx
  client/src/tests/modules/teams/components/MemberCard.test.jsx
  client/src/tests/modules/teams/components/Project.test.jsx
  client/src/tests/modules/teams/teamsMockData.js
Labels: Ready for merge

#43 #161117046 Common Module Tests
  client/src/modules/common/Modals/AddIntegration.jsx
  client/src/modules/common/Navbar/index.jsx
  client/src/modules/common/Preloader/index.jsx
  client/src/tests/modules/common/Footer/index.test.jsx
  client/src/tests/modules/common/Modals/AddIntegration.test.jsx
  client/src/tests/modules/common/Modals/AddMember.test.jsx
  client/src/tests/modules/common/Navbar/index.test.jsx
  client/src/tests/modules/common/Preloader/index.test.jsx
  client/src/tests/modules/common/Spinner/Spinner.test.jsx
Labels: Ready for code review

#61 #161246353 Request To Join Team Page
  client/src/modules/Teams/container/Join.jsx
  client/src/routes/index.jsx
  client/src/tests/modules/teams/container/Join.test.jsx
  client/styles/components/_teams.scss
Labels: Ready for code review

#62 #161378723 Account invitation status
  client/src/modules/Teams/components/InviteMembers.jsx
  client/src/redux/reducers/teamsReducer.js
  client/src/tests/modules/teams/components/InviteMembers.test.jsx
  client/src/tests/modules/teams/teamsMockData.js
  client/src/tests/redux/reducers/teamReducer.test.js
  client/src/tests/toasts.js/memberInvitationStatus.test.jsx
  client/src/toasts/memberInvitationStatus.jsx
  client/styles/components/_create_team.scss
Labels: Ready for code review

#63 #161360168 Add tooltip to create-team form visual feedback
  client/src/redux/actions/teams/index.js
  client/src/toasts/VisualFeedback.jsx
  client/styles/components/_create_team.scss
Labels: Ready for code review

#64 #161423307 Add role input field in the member invitation form
  client/src/modules/Teams/components/InviteMembers.jsx
  client/src/redux/actions/teams/members.js
  client/src/tests/__mocks__/__mockData__/memberMock.js
  client/src/tests/modules/teams/components/InviteMembers.test.jsx
  client/styles/components/_create_team.scss
  client/styles/components/_teams.scss
Labels: Ready for code review

#59 #161246353: team lead create share link
  client/public/resources/images/copy.png
  client/src/modules/Teams/components/Dropdown.jsx
  client/src/modules/Teams/components/InviteForm.jsx
  client/src/modules/Teams/components/InviteMembers.jsx
  client/src/modules/Teams/components/Member.jsx
  client/src/modules/Teams/components/MultiValueLabel.jsx
  client/src/modules/Teams/components/ShareLink.jsx
  client/src/modules/Teams/container/index.jsx
  client/src/redux/actions/requests/index.js
  client/src/redux/reducers/requestsReducer.js
  client/src/routes/AuthRoute.jsx
  client/src/setupEnzyme.js
  client/src/tests/modules/teams/components/Dropdown.test.jsx
  client/src/tests/modules/teams/components/InviteForm.test.jsx
  client/src/tests/modules/teams/components/MultiValueLabel.test.jsx
  client/src/tests/modules/teams/components/ShareLink.test.jsx
  client/src/tests/redux/actions/requests/index.test.js
  client/styles/components/_invite_form.scss
  client/styles/styles.scss
  jest.config.js
  package-lock.json
  package.json
Labels: Ready for code review, Ready for merge

#66 #161412091 Admin should be able to see admin requests
  client/src/modules/Admin/components/AdminRequest.jsx
  client/src/modules/HOC/withRequests.jsx
  client/src/modules/common/Pagination/index.jsx
  client/src/redux/actions/requests/index.js
  client/src/tests/modules/Admin/components/AdminRequests.test.jsx
  client/src/tests/modules/HOC/withRequests.test.jsx
  client/src/tests/redux/actions/requests/index.test.js
  package-lock.json
Labels: Ready for code review

#67 #161246353: team lead should accept request
  client/src/modules/Admin/components/AdminRequest.jsx
  client/src/modules/Admin/components/RequestCheckbox.jsx
  client/src/modules/HOC/withRequests.jsx
  client/src/modules/Teams/components/JoinTeamRequests.jsx
  client/src/modules/Teams/components/Member.jsx
  client/src/modules/Teams/container/Join.jsx
  client/src/tests/modules/teams/components/JoinTeamRequests.test.jsx
  client/styles/components/_request_checkbox.scss
  client/styles/styles.scss
Labels: Ready for code review
